const championNameMap = {
    "TFT14_Alistar": "알리스타",
    "TFT14_DrMundo": "문도 박사",
    "TFT14_Jax": "잭스",
    "TFT14_Kindred": "킨드레드",
    "TFT14_KogMaw": "코그모",
    "TFT14_Morgana": "모르가나",
    "TFT14_Nidalee": "니달리",
    "TFT14_Poppy": "뽀삐",
    "TFT14_Seraphine": "세라핀",
    "TFT14_Shaco": "샤코",
    "TFT14_Sylas": "사일러스",
    "TFT14_Vi": "바이",
    "TFT14_Zyra": "자이라",
  
    "TFT14_Darius": "다리우스",
    "TFT14_Ekko": "에코",
    "TFT14_Graves": "그레이브즈",
    "TFT14_Illaoi": "일라오이",
    "TFT14_Jhin": "진",
    "TFT14_LeBlanc": "르블랑",
    "TFT14_Naafiri": "나피리",
    "TFT14_Rhaast": "라아스트",
    "TFT14_Shyvana": "쉬바나",
    "TFT14_Skarner": "스카너",
    "TFT14_TwistedFate": "트위스티드 페이트",
    "TFT14_Vayne": "베인",
    "TFT14_Veigar": "베이가",
  
    "TFT14_Braum": "브라움",
    "TFT14_Draven": "드레이븐",
    "TFT14_Elise": "엘리스",
    "TFT14_Fiddlesticks": "피들스틱",
    "TFT14_Galio": "갈리오",
    "TFT14_Gragas": "그라가스",
    "TFT14_Jarvan": "자르반 4세",
    "TFT14_Jinx": "징크스",
    "TFT14_Mordekaiser": "모르데카이저",
    "TFT14_Rengar": "렝가",
    "TFT14_Senna": "세나",
    "TFT14_Varus": "바루스",
    "TFT14_Yuumi": "유미",
  
    "TFT14_Annie": "애니",
    "TFT14_Aphelios": "아펠리오스",
    "TFT14_Brand": "브랜드",
    "TFT14_ChoGath": "초가스",
    "TFT14_Leona": "레오나",
    "TFT14_MissFortune": "미스 포츈",
    "TFT14_Neeko": "니코",
    "TFT14_Sejuani": "세주아니",
    "TFT14_Vex": "벡스",
    "TFT14_Xayah": "자야",
    "TFT14_Zed": "제드",
    "TFT14_Zeri": "제리",
    "TFT14_Ziggs": "직스",
  
    "TFT14_Aurora": "오로라",
    "TFT14_Garen": "가렌",
    "TFT14_Kobuko": "코부코",
    "TFT14_Renekton": "레넥톤",
    "TFT14_Samira": "사미라",
    "TFT14_Urgot": "우르곳",
    "TFT14_Viego": "비에고",
    "TFT14_Zac": "자크",

    // TFT14_
    "T43X": "T43X",
  };

  export default championNameMap;