const itemNameMap = {

    //조합아이템

    "TFT_Item_BFSword": "BF 대검",
    "TFT_Item_ChainVest": "쇠사슬 조끼",
    "TFT_Item_GiantsBelt": "거인의 허리띠",
    "TFT_Item_NeedlesslyLargeRod": "쓸데없이 큰 지팡이",
    "TFT_Item_NegatronCloak": "음전자 망토",
    "TFT_Item_RecurveBow": "곡궁",
    "TFT_Item_SparringGloves": "연습용 장갑",
    "TFT_Item_TearOfTheGoddess": "여신의 눈물",

    //완성아이템

    "TFT_Item_AdaptiveHelm": "적응형 투구",
    "TFT_Item_SteraksGage": "스테락의 도전",
    "TFT_Item_Quicksilver": "수은",
    "TFT_Item_Deathblade": "죽음의 검",
    "TFT_Item_ThiefsGloves": "도적의 장갑",
    "TFT_Item_PowerGauntlet": "방패파괴자",
    "TFT_Item_NightHarvester": "굳건한 심장",
    "TFT_Item_GuardianAngel": "밤의 끝자락",
    "TFT_Item_Crownguard": "크라운가드",
    "TFT_Item_RunaansHurricane": "루난의 허리케인",
    "TFT_Item_MadredsBloodrazor": "거인 학살자",
    "TFT_Item_StatikkShiv": "스태틱의 단검",
    "TFT_Item_RabadonsDeathcap": "라바돈의 죽음모자",
    "TFT_Item_FrozenHeart": "수호자의 맹세",
    "TFT_Item_Morellonomicon": "모렐로노미콘",
    "TFT_Item_TacticiansRing": "전략가의 망토",
    "TFT_Item_Redemption": "구원",
    "TFT_Item_IonicSpark": "이온 충격기",
    "TFT_Item_HextechGunblade": "마법공학 총검",
    "TFT_Item_RapidFireCannon": "붉은 덩굴정령",
    "TFT_Item_BrambleVest": "덤불 조끼",
    "TFT_Item_SpectralGauntlet": "저녁갑주",
    "TFT_Item_UnstableConcoction":"정의의 손길",
    "TFT_Item_TitansResolve":"거인의 결의",
    "TFT_Item_LastWhisper":"최후의 속삭임",
    "TFT_Item_Bloodthirster":"피바라기",
    "TFT_Item_TacticiansScepter":"전략가의 방패",
    "TFT_Item_WarmogsArmor":"워모그의 갑옷",
    "TFT_Item_BlueBuff":"푸른 파수꾼",
    "TFT_Item_Leviathan":"내셔의 이빨",
    "TFT_Item_ArchangelsStaff":"대천사의 지팡이",
    "TFT_Item_RedBuff":"태양불꽃 망토",
    "TFT_Item_DragonsClaw":"용의 발톱",
    "TFT_Item_ForceOfNature":"전략가의 왕관",
    "TFT_Item_JeweledGauntlet":"보석건틀릿",
    "TFT_Item_InfinityEdge":"무한의 대검",
    "TFT_Item_GargoyleStoneplate":"가고일 돌갑옷",
    "TFT_Item_GuinsoosRageblade":"구인수의 격노검",
    "TFT_Item_SpearOfShojin":"쇼진의 창",

    //찬란한 아이템
    "TFT5_Item_NightHarvesterRadiant":"거석상의 유산",
    "TFT5_Item_RunaansHurricaneRadiant":"루난의 폭풍",
    "TFT5_Item_GargoyleStoneplateRadiant":"수호상 돌갑옷",
    "TFT5_Item_HextechGunbladeRadiant":"마법공학 생명검",
    "TFT5_Item_StatikkShivRadiant":"스태틱의 호의",
    "TFT5_Item_SteraksGageRadiant":"스테락의 초강력 보호막",
    "TFT5_Item_GiantSlayerRadiant":"악마 학살자",
    "TFT5_Item_RedemptionRadiant":"면죄",
    "TFT5_Item_InfinityEdgeRadiant":"천공의 대검",
    "TFT5_Item_CrownguardRadiant":"왕가의 방패",
    "TFT5_Item_SpectralGauntletRadiant":"별의 균형",
    "TFT5_Item_GuinsoosRagebladeRadiant":"구인수의 심판",
    "TFT5_Item_HandOfJusticeRadiant":"공정의 주먹",
    "TFT5_Item_TitansResolveRadiant":"거인의 맹세",
    "TFT5_Item_ThiefsGlovesRadiant":"장난꾸러기의 장갑",
    "TFT5_Item_MorellonomiconRadiant":"엔젤로노미콘",
    "TFT5_Item_BloodthirsterRadiant":"축복받은 피바라기",
    "TFT5_Item_WarmogsArmorRadiant":"워모그의 자부심",
    "TFT5_Item_SunfireCapeRadiant":"태양빛 망토",
    "TFT5_Item_BlueBuffRadiant":"푸른 축복",
    "TFT5_Item_LastWhisperRadiant":"영겁의 속삭임",
    "TFT5_Item_SpearOfShojinRadiant":"히라나의 창",
    "TFT5_Item_FrozenHeartRadiant":"철갑의 서약",
    "TFT5_Item_QuicksilverRadiant":"반짝이는 수은",
    "TFT5_Item_BrambleVestRadiant":"장미가시 조끼",
    "TFT5_Item_IonicSparkRadiant":"집단 충격기",
    "TFT5_Item_AdaptiveHelmRadiant":"해신 작쇼",
    "TFT5_Item_JeweledGauntletRadiant":"눈부신 건틀릿",
    "TFT5_Item_GuardianAngelRadiant":"새벽의 서광",
    "TFT5_Item_TrapClawRadiant":"의지파괴자",
    "TFT5_Item_RabadonsDeathcapRadiant":"라바돈의 초월한 죽음모자",
    "TFT5_Item_RapidFirecannonRadiant":"잉걸불 문장",
    "TFT5_Item_DeathbladeRadiant":"빛나는 죽음의 검",
    "TFT5_Item_DragonsClawRadiant":"용의 의지",
    "TFT5_Item_LeviathanRadiant":"남작의 선물",
    "TFT5_Item_ArchangelsStaffRadiant":"우르프 천사의 지팡이",

    //지원아이템

    "TFT_Item_AegisOfTheLegion": "군단의 방패",
    "TFT_Item_BansheesVeil":"밴시의 장막",
    "TFT_Item_Chalice":"힘의 성배",
    "TFT_Item_EternalFlame":"영원한 불꽃",
    "TFT_Item_LocketOfTheIronSolari":"강철의 솔라리 펜던트",
    "TFT_Item_Moonstone":"월석 재생기",
    "TFT_Item_RadiantVirtue":"순교자의 미덕",
    "TFT_Item_Spite":"앙심",
    "TFT_Item_SupportKnightsVow":"기사의 맹세",
    "TFT_Item_UnstableTreasureChest":"불안정한 보물상자",
    "TFT_Item_ZekesHerald":"지크의 전령",
    "TFT_Item_Zephyr":"서풍",
    "TFT7_Item_ShimmerscaleHeartOfGold":"쓸데없이 큰 보석",
    "TFT4_Item_OrnnRanduinsSanctum":"란두인의 예언",
    "TFT4_Item_OrnnObsidianCleaver":"흑요석 양날 도끼",
    "TFT5_Item_ZzRotPortalRadiant":"즈롯 차원문",
    "TFT_Item_Shroud":"침묵의 장갑",

    //유물아이템

    "TFT_Item_Artifact_BlightingJewel":"역병의 보석",
    "TFT_Item_Artifact_Fishbones":"생선대가리",
    "TFT_Item_Artifact_HorizonFocus":"지평선의 초점",
    "TFT_Item_Artifact_InnervatingLocket":"활력증진의 펜던트",
    "TFT_Item_Artifact_LichBane":"리치베인",
    "TFT_Item_Artifact_LightshieldCrest":"라이트실드 문장",
    "TFT_Item_Artifact_LudensTempest":"루덴의 폭풍",
    "TFT_Item_Artifact_Mittens":"방한장갑",
    "TFT_Item_Artifact_ProwlersClaw":"자객의 발톱",
    "TFT_Item_Artifact_RapidFirecannon":"고속연사포",
    "TFT_Item_Artifact_SeekersArmguard":"추적자의 팔목 보호대",
    "TFT_Item_Artifact_SilvermereDawn":"은빛여명",
    "TFT_Item_Artifact_SpectralCutlass":"망령 해적검",
    "TFT_Item_Artifact_SuspiciousTrenchCoat":"수상한 외투",
    "TFT_Item_Artifact_TalismanOfAscension":"승천의 부적",
    "TFT_Item_Artifact_UnendingDespair":"끝없는 절망",
    "TFT_Item_Artifact_WitsEnd":"마법사의 최후",
    "TFT4_Item_OrnnAnimaVisage":"정령의 형상",
    "TFT4_Item_OrnnDeathsDefiance":"죽음의 무도",
    "TFT4_Item_OrnnInfinityForce":"무한한 삼위일체",
    "TFT4_Item_OrnnMuramana":"마나자네",
    "TFT4_Item_OrnnTheCollector":"징수의 총",
    "TFT4_Item_OrnnZhonyasParadox":"존야의 모래시계",
    "TFT7_Item_ShimmerscaleGamblersBlade":"도박꾼의 칼날",
    "TFT7_Item_ShimmerscaleMogulsMail":"거물의 갑옷",
    "TFT9_Item_OrnnDeathfireGrasp":"죽음불꽃 손아귀",
    "TFT9_Item_OrnnHorizonFocus":"저격수의 집중",
    "TFT9_Item_OrnnHullbreaker":"선체 파괴자",
    "TFT9_Item_OrnnTrickstersGlass":"속임수 거울",

    //상징
    "TFT14_Item_ControllerEmblemItem":"책략가 상징",
    "TFT14_Item_DivinicorpEmblemItem":"신성기업 상징",
    "TFT14_Item_ArmorcladEmblemItem":"요새 상징",
    "TFT14_Item_StrongEmblemItem":"학살자 상징",
    "TFT14_Item_SwiftEmblemItem":"속사포 상징",
    "TFT14_Item_TechieEmblemItem":"기술광 상징",
    "TFT14_Item_ThirstyEmblemItem":"다이나모 상징",
    "TFT14_Item_VanguardEmblemItem":"선봉대 상징",
    "TFT14_Item_BallisTekEmblemItem":"폭발 봇 상징",
    "TFT14_Item_ImmortalEmblemItem":"황금황소 상징",
    "TFT14_Item_DarkWebEmblemItem":"동물특공대 상징",
    "TFT14_Item_MobEmblemItem":"범죄조직 상징",
    "TFT14_Item_MarksmanEmblemItem":"사격수 상징",
    "TFT14_Item_EdgeRunnerEmblemItem":"엑소테크 상징",
    "TFT14_Item_CutterEmblemItem":"처형자 상징",
    "TFT14_Item_StreetDemonEmblemItem":"거리의 악마 상징",
    "TFT14_Item_BruiserEmblemItem":"난동꾼 상징",
    
    //14시즌 엑소테크 아이템
    "TFT14_JaxCyberneticItem":"추진기 가로등",
    "TFT14_JaxCyberneticItem_Radiant":"무효화 가로등",
    "TFT14_JhinCyberneticItem":"맥박 안정화 장치",
    "TFT14_JhinCyberneticItem_Radiant":"맥박 억제기",
    "TFT14_MordekaiserCyberneticItem":"타락한 몸체",
    "TFT14_MordekaiserCyberneticItem_Radiant":"조화로운 몸제",
    "TFT14_NaafiriCyberneticItem":"하이퍼 송곳니",
    "TFT14_NaafiriCyberneticItem_Radiant":"최첨단 송곳니",
    "TFT14_SejuaniCyberneticItem":"사이버 코일",
    "TFT14_SejuaniCyberneticItem_Radiant":"강탈한 사이버 코일",
    "TFT14_VarusCyberneticItem":"홀로그램 활",
    "TFT14_VarusCyberneticItem_Radiant":"조준경 부착 홀로그램 활",
    "TFT14_ZeriCyberneticItem":"유동 콘덴서",
    "TFT14_ZeriCyberneticItem_Radiant":"완충된 유동 콘덴서",

    //14시즌 니트로 아이템
    "TFT14_Item_Nitro_ChromeCounter":"크롬",
}

export default itemNameMap;