const traitsNameMap = {
    "TFT14_AnimaSquad":"동물특공대",
    "TFT14_Armorclad":"요새",
    "TFT14_BallisTek":"폭발 봇",
    "TFT14_Bruiser":"난동꾼",
    "TFT14_Controller":"책략가",
    "TFT14_Cutter":"처형자",
    "TFT14_Cyberboss":"사이버보스",
    "TFT14_Divinicorp":"신성기업",
    "TFT14_EdgeRunner":"엑소테크",
    "TFT14_HotRod":"니트로",
    "TFT14_Immortal":"황금황소",
    "TFT14_Marksman":"사격수",
    "TFT14_Mob":"범죄조직",
    "TFT14_Netgod":"네트워크의 신",
    "TFT14_Overlord":"군주",
    "TFT14_StreetDemon":"거리의 악마",
    "TFT14_Strong":"학살자",
    "TFT14_Suits":"사이퍼",
    "TFT14_Supercharge":"증.폭.",
    "TFT14_Swift":"속사포",
    "TFT14_Techie":"기술광",
    "TFT14_Thirsty":"다이나모",
    "TFT14_Vanguard":"선봉대",
    "TFT14_ViegoUniqueTrait":"영혼살해자",
    "TFT14_Virus":"바이러스",
}

export default traitsNameMap